= waitproc -- Wait for an arbitrary process
:toc: left
:syntax-highlighter: coderay

The wait family of system calls and the wait Bash built-in command
allow one to wait for child process, while this command allows one to
wait for an arbitrary process.

* Homepage: <http://linuxbox.fi/~vmj/waitproc/>
* Download: <http://linuxbox.fi/~vmj/waitproc/archive/>
* Source code: <http://github.com/vmj/waitproc>

== Basic usage

The program http://www.linuxbox.fi/~vmj/waitproc/waitproc.1.html[waitproc(1)]
waits for process whose process ID (PID) is given on the command line.
Following shows a typical invocation:

----
$ waitproc 12345
----

== Requirements

At runtime, GNU C libraries on Linux.

To compile, GNU Make, AsciiDoc, and xmlto are required.
On Debian based systems, you can install `asciidoc` and `xmlto` packages.
On Slackware, `linuxdoc-tools` contains both the `asciidoc` and `xmlto` tools.

== Installation

Type `make install` to install the binary into '/usr/local/bin' and
manual page to '/usr/local/man/man1'.

You can also define `PREFIX` to install waitproc in a different prefix:
`make install PREFIX=/usr` for example.
Similarly, there's `DESTDIR`, `BINDIR`, `MANDIR`, and `MAN1DIR` for those who need them.

== Authors

Original author and current maintainer is Mikko Värri
(vmj@linuxbox.fi).

== License

waitproc is Free Software, licensed under GNU General Public License
(GPL), version 3 or later.  See `LICENSE.txt` file for details.
